#!/usr/bin/env python3
# Extract per-glyph ink metrics (em-normalized) from the bundled fonts for the
# Align (ink-metric / approach B) demo. Regenerates src/mockup-metrics-data.js.
# Usage: python3 scripts/extract-mockup-metrics.py  (run from module root)
import json
from fontTools.ttLib import TTFont
from fontTools.pens.boundsPen import BoundsPen

FONTS = {
    "SUIT": ("fonts/SUIT-Heavy.woff2", "900"),
    "Glow": ("fonts/GlowSansSC-Heavy.woff2", "900"),
    "Mono": ("fonts/NotoSansMono-Bold.ttf", "700"),
}
ascii_chars = [chr(c) for c in range(0x20, 0x7f)]
CHARS = {
    "SUIT": list("출력시스템가") + ascii_chars,
    "Glow": list("系统林"),
    "Mono": ascii_chars,
}


def glyph_metrics(path, chars):
    font = TTFont(path)
    upm = font["head"].unitsPerEm
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    out = {}
    for ch in chars:
        cp = ord(ch)
        if cp not in cmap:
            continue
        gname = cmap[cp]
        adv = hmtx[gname][0] / upm
        pen = BoundsPen(gs)
        gs[gname].draw(pen)
        if pen.bounds is None:
            out[ch] = {"adv": round(adv, 4), "l": 0, "r": round(adv, 4), "t": 0, "b": 0}
        else:
            xMin, yMin, xMax, yMax = pen.bounds
            out[ch] = {
                "adv": round(adv, 4),
                "l": round(xMin / upm, 4),
                "r": round(xMax / upm, 4),
                "t": round(yMax / upm, 4),
                "b": round(yMin / upm, 4),
            }
    return out


def main():
    data = {fam: {w: glyph_metrics(p, CHARS[fam])} for fam, (p, w) in FONTS.items()}
    js = "// GENERATED by scripts/extract-mockup-metrics.py — do not edit by hand.\n"
    js += "// Per-glyph ink metrics (em-normalized) for the Align (ink-metric) demo.\n"
    js += "export const MOCKUP_METRICS = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    with open("src/mockup-metrics-data.js", "w", encoding="utf-8") as f:
        f.write(js)
    print("wrote src/mockup-metrics-data.js")


if __name__ == "__main__":
    main()
