// Extension point: add vocabulary, date labels, and fake data labels here.
export const visualTokens = {
  koreanKeywords: [
    "접속", "검증", "회로", "출력", "신호", "제어", "기록", "연산",
    "동기", "방식", "전원", "해석", "단말", "기준", "응답", "흐름"
  ],
  hanjaKeywords: ["林"],
  greetingTokens: [
    { value: "안녕?", typeface: "korean" },
    { value: "你好?", typeface: "chinese" },
    { value: "HELLO?", typeface: "english" }
  ],
  englishKeywords: [
    "ACCESS", "OUTPUT", "VERIFIED", "STANDBY", "RUNNING", "SIGNAL",
    "VECTOR", "STATUS", "MODULE", "CIRCUIT", "LOCKED", "SYSTEM",
    "FIELD", "REPORT", "QUEUE", "INPUT"
  ],
  statusCodes: ["200", "301", "400", "403", "404", "500", "503"],
  actionTokens: [
    { english: "BUY", korean: "구매", chinese: "购买" },
    { english: "USE", korean: "사용", chinese: "使用" },
    { english: "BREAK", korean: "분해", chinese: "拆解" },
    { english: "FIX", korean: "수리", chinese: "修复" },
    { english: "TRASH", korean: "폐기", chinese: "丢弃" },
    { english: "CHANGE", korean: "변경", chinese: "更改" },
    { english: "MAIL", korean: "메일", chinese: "邮件" },
    { english: "UPGRADE", korean: "업그레이드", chinese: "升级" },
    { english: "CHARGE", korean: "충전", chinese: "充电" },
    { english: "POINT", korean: "지시", chinese: "指向" },
    { english: "ZOOM", korean: "확대", chinese: "缩放" },
    { english: "PRESS", korean: "누르기", chinese: "按下" },
    { english: "SNAP", korean: "캡처", chinese: "快照" },
    { english: "WORK", korean: "작동", chinese: "运作" },
    { english: "QUICK", korean: "빠르게", chinese: "快速" },
    { english: "ERASE", korean: "삭제", chinese: "擦除" },
    { english: "WRITE", korean: "쓰기", chinese: "写入" },
    { english: "CUT", korean: "잘라내기", chinese: "剪切" },
    { english: "PASTE", korean: "붙여넣기", chinese: "粘贴" },
    { english: "SAVE", korean: "저장", chinese: "保存" },
    { english: "LOAD", korean: "불러오기", chinese: "加载" },
    { english: "CHECK", korean: "확인", chinese: "检查" },
    { english: "REWRITE", korean: "다시쓰기", chinese: "重写" },
    { english: "PLUG", korean: "연결", chinese: "接入" },
    { english: "PLAY", korean: "재생", chinese: "播放" },
    { english: "BURN", korean: "굽기", chinese: "刻录" },
    { english: "RIP", korean: "추출", chinese: "提取" },
    { english: "DRAG AND DROP", korean: "드래그앤드롭", chinese: "拖放" },
    { english: "ZIP", korean: "압축", chinese: "压缩" },
    { english: "UNZIP", korean: "압축해제", chinese: "解压" },
    { english: "LOCK", korean: "잠금", chinese: "锁定" },
    { english: "FILL", korean: "채우기", chinese: "填充" },
    { english: "CALL", korean: "호출", chinese: "调用" },
    { english: "FIND", korean: "찾기", chinese: "查找" },
    { english: "VIEW", korean: "보기", chinese: "查看" },
    { english: "CODE", korean: "코딩", chinese: "编码" },
    { english: "JAM", korean: "재밍", chinese: "干扰" },
    { english: "UNLOCK", korean: "잠금해제", chinese: "解锁" },
    { english: "SURF", korean: "탐색", chinese: "浏览" },
    { english: "SCROLL", korean: "스크롤", chinese: "滚动" },
    { english: "PAUSE", korean: "일시정지", chinese: "暂停" },
    { english: "CLICK", korean: "클릭", chinese: "点击" },
    { english: "CROSS", korean: "교차", chinese: "交叉" },
    { english: "CRACK", korean: "해독", chinese: "破解" },
    { english: "SWITCH", korean: "전환", chinese: "切换" },
    { english: "UPDATE", korean: "업데이트", chinese: "更新" },
    { english: "NAME", korean: "명명", chinese: "命名" },
    { english: "READ", korean: "읽기", chinese: "读取" },
    { english: "TUNE", korean: "조정", chinese: "调整" },
    { english: "PRINT", korean: "인쇄", chinese: "打印" },
    { english: "SCAN", korean: "스캔", chinese: "扫描" },
    { english: "SEND", korean: "전송", chinese: "发送" },
    { english: "FAX", korean: "팩스", chinese: "传真" },
    { english: "RENAME", korean: "이름변경", chinese: "重命名" },
    { english: "TOUCH", korean: "터치", chinese: "触摸" },
    { english: "BRING", korean: "가져오기", chinese: "导入" },
    { english: "PAY", korean: "결제", chinese: "支付" },
    { english: "WATCH", korean: "감시", chinese: "监视" },
    { english: "TURN", korean: "회전", chinese: "旋转" },
    { english: "LEAVE", korean: "종료", chinese: "退出" },
    { english: "START", korean: "시작", chinese: "启动" },
    { english: "FORMAT", korean: "포맷", chinese: "格式化" }
  ],
  organizationPrefixes: [
    "RADIAN", "NOVA", "ATLAS", "ORBITAL", "CARGO", "COBALT",
    "SUMMIT", "VECTOR", "MERIDIAN", "HELIX", "AXIOM", "DELTA"
  ],
  organizationSuffixes: ["LABS", "WORKS", "STUDIO", "DIVISION", "SYSTEMS", "ENGINEERING", "INDUSTRIES", "OFFICE"],
  tableFieldLabels: ["LOT", "SPEC", "FREQ", "LOAD", "REV", "TEMP", "POWER", "LAT", "CFG"],
  dateTypography: {
    englishMonths: ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"],
    englishMonthShort: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"],
    chineseDigits: ["〇", "一", "二", "三", "四", "五", "六", "七", "八", "九"],
    refreshedLabels: { korean: "갱신", english: "REFRESHED", chinese: "刷新" },
    timestampLabels: { korean: "타임스탬프", english: "TIMESTAMP", chinese: "时间戳" }
  }
};
